{{- with .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-config
  labels:
    {{- include "fairwinds-insights.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml . | nindent 4 }}
{{- end }}
