apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-executor
  labels:
    app: fairwinds-insights
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-executor
  labels:
    app: fairwinds-insights
rules:
- apiGroups: [""]
  resources: ["cronjobs"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-executor
  labels:
    app: fairwinds-insights
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cronjob-executor
subjects:
- kind: ServiceAccount
  name: cronjob-executor
  namespace: {{ .Release.Namespace }}
