{{- if .Values.ingress.enabled }}
{{- if not (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") }}
{{- if not .Values.ingress.separate }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: cert
      hosts:
        {{- range .Values.ingress.hostedZones }}
        - {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
        {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hostedZones }}
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/v0/*" "/v0" }}
            backend:
              serviceName: api
              servicePort: http
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/swagger/*" "/swagger" }}
            backend:
              serviceName: open-api
              servicePort: http
          - path: {{ $.Values.ingress.starPaths | ternary "/*" "/" }}
            backend:
              serviceName: dashboard
              servicePort: http
    {{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- if .Values.ingress.api }}
    {{ with .Values.ingress.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: cert
      hosts:
        {{- range .Values.ingress.hostedZones }}
        - {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
        {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hostedZones }}
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/v0/*" "/v0" }}
            backend:
              serviceName: api
              servicePort: http
    {{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- if .Values.ingress.dashboard }}
    {{ with .Values.ingress.dashboard.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: cert
      hosts:
        {{- range .Values.ingress.hostedZones }}
        - {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
        {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hostedZones }}
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/swagger/*" "/swagger" }}
            backend:
              serviceName: open-api
              servicePort: http
          - path: {{ $.Values.ingress.starPaths | ternary "/*" "/" }}
            backend:
              serviceName: dashboard
              servicePort: http
    {{- end }}
{{- end }}
{{- else }}
{{- if not .Values.ingress.separate }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: cert
      hosts:
        {{- range .Values.ingress.hostedZones }}
        - {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
        {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hostedZones }}
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/swagger/*" "/swagger" }}
            pathType: Prefix
            backend:
              service:
                name: open-api
                port:
                  name: http
          - path: {{ $.Values.ingress.starPaths | ternary "/v0/*" "/v0" }}
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: {{ $.Values.ingress.starPaths | ternary "/*" "/" }}
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  name: http
    {{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- if .Values.ingress.api }}
    {{ with .Values.ingress.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: cert
      hosts:
        {{- range .Values.ingress.hostedZones }}
        - {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
        {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hostedZones }}
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/v0*" "/v0" }}
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- if .Values.ingress.dashboard }}
    {{ with .Values.ingress.dashboard.annotations }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
    {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: cert
      hosts:
        {{- range .Values.ingress.hostedZones }}
        - {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
        {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hostedZones }}
    - host: {{ include "fairwinds-insights.sanitizedPrefix" $ }}{{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.starPaths | ternary "/swagger/*" "/swagger" }}
            pathType: Prefix
            backend:
              service:
                name: open-api
                port:
                  name: http
          - path: {{ $.Values.ingress.starPaths | ternary "/*" "/" }}
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  name: http
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
