apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights
  {{ with .Values.rbac.serviceAccount.annotations }}
  annotations:
  {{-   range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{-   end }}
  {{- end }}
---
{{- if .Values.options.insightsSAASHost }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-kubesystem
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - kube-system
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-kubesystem
subjects:
- kind: ServiceAccount
  name: insights
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: view-kubesystem
  apiGroup: rbac.authorization.k8s.io
{{- end }}
