apiVersion: v2
appVersion: "6.5.2"
description: A Helm chart to run the Fairwinds Insights server
name: fairwinds-insights
version: 0.3.0
maintainers:
- name: rbren
- name: makoscafee
- name: ivanfetch-fw
dependencies:
- name: postgresql
  version: 9.1.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.ephemeral
- name: minio
  version: 5.0.32
  repository: https://helm.min.io/
  condition: minio.install
